### ISSUE TITLE
Nothing happens after I drag .sav file onto .bat file

### ISSUE THREAD

**Issue by Jernee** [cheahjs/palworld-save-tools#10]
The .bat file runs and the cmd opens up but once I hit Y the file doesn't change.

**Comment by Cr4nkSt4r** [comment]
Because the .bat doesn't either change the directory to where the python scripts are or isn't executing them from the previous directory.
You should be able to just copy the bat files into the main folder where the python scripts are, if you don't know how to edit .bat files.

Or just download the [Release](https://github.com/cheahjs/palworld-save-tools/releases/) zip file.

**Comment by Jernee** [comment]
> Because the .bat doesn't either change the directory to where the python scripts are or isn't executing them from the previous directory. You should be able to just copy the bat files into the main folder where the python scripts are, if you don't know how to edit .bat files.
> 
> Or just download the [Release](https://github.com/cheahjs/palworld-save-tools/releases/) zip file.

I did download the release zip file. Only thing I changed was the python to py because it was saying I didn't have python installed.

**Comment by Jernee** [comment]
https://github.com/cheahjs/palworld-save-tools/issues/21#issuecomment-1912225168
